### ISSUE TITLE
Extenstion Autoremoved by Chrome

### ISSUE THREAD

**Issue by afedulov** [Pauan/tab-organizer#180]
Hi! Your awesome extention got removed and this is what Chrome Store says:

![image](https://user-images.githubusercontent.com/1492164/40785074-cb624dc6-64e7-11e8-8a6d-ed6687cb9a1d.png)

Would greatly appreciate the fix! Thanks!

**Comment by mikhoul** [comment]
@afedulov This extension is migrating to Firefox so I suggest you to use: "Sync Tab Groups" which is actively developed and with more features: https://morikko.github.io/synctabgroups/


Regards :octocat:

**Comment by afedulov** [comment]
@mikhoul unfortunately this is not what I need. I already have Toby for this kind of functionality. What I am missing is the ability search across all the tabs by the page title, which synctabgroups does not allow. Columnar representation of all open windows and the ability to quickly reorder is also something I would like to have. Pretty much exactly what Tab Organizer is.

**Comment by Pauan** [comment]
@afedulov Thanks for letting me know! I'll try and get a fixed version published ASAP.

However, I haven't worked on this extension in a very long time, it's not really maintained, so it's unlikely that I'll fix anything other than the immediate problems (like this issue).

**Comment by Pauan** [comment]
Okay, I published a fixed version, let me know if it works for you.

**Comment by afedulov** [comment]
Thanks a lot, it works!
